In [48]:
import pandas as pd
from keras.datasets import cifar100

In [49]:
cifar100.load_data()

((array([[[[255, 255, 255],
           [255, 255, 255],
           [255, 255, 255],
           ...,
           [195, 205, 193],
           [212, 224, 204],
           [182, 194, 167]],
  
          [[255, 255, 255],
           [254, 254, 254],
           [254, 254, 254],
           ...,
           [170, 176, 150],
           [161, 168, 130],
           [146, 154, 113]],
  
          [[255, 255, 255],
           [254, 254, 254],
           [255, 255, 255],
           ...,
           [189, 199, 169],
           [166, 178, 130],
           [121, 133,  87]],
  
          ...,
  
          [[148, 185,  79],
           [142, 182,  57],
           [140, 179,  60],
           ...,
           [ 30,  17,   1],
           [ 65,  62,  15],
           [ 76,  77,  20]],
  
          [[122, 157,  66],
           [120, 155,  58],
           [126, 160,  71],
           ...,
           [ 22,  16,   3],
           [ 97, 112,  56],
           [141, 161,  87]],
  
          [[ 87, 122,  41],
           [ 8

In [50]:
(train_i, train_l), (test_i, test_l) = cifar100.load_data(label_mode='fine')
df_train_i=pd.DataFrame(train_i.reshape(train_i.shape[0],-1))
df_train_i.head()

0     1     2     3     4     5     6     7     8     9     ...  3062  \
0   255   255   255   255   255   255   255   255   255   255  ...     4   
1   255   255   255   253   253   253   253   253   253   253  ...   253   
2   250   250   248   248   249   243   247   248   239   248  ...   190   
3   124   194   221   131   202   228   135   206   228   138  ...   223   
4    43    49    46    32    40    34    87    89    47   127  ...    78   

   3063  3064  3065  3066  3067  3068  3069  3070  3071  
0    34    36    10   105   133    59   138   173    79  
1   253   253   253   253   253   253   255   255   255  
2   219   209   194   223   216   207   232   230   228  
3   230   237   232   243   237   236   243   230   231  
4    93    88    60    55    55    29    63    67    37  

[5 rows x 3072 columns]

In [8]:
train_i.shape

(50000, 32, 32, 3)

In [9]:
train_l.shape

(50000, 1)

In [51]:
from keras.models import Sequential
from keras.layers import Dense
from keras import models, layers
network=models.Sequential()
network.add(layers.Dense(512,activation='relu',input_shape=(32*32*3,)))
network.add(layers.Dense(100,activation='softmax'))

In [61]:
from keras.optimizers import RMSprop  # Import the RMSprop optimizer

network.compile(optimizer=RMSprop(learning_rate=0.0001),
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [53]:
from keras.utils import to_categorical
train_l=to_categorical(train_l)
test_l=to_categorical(test_l)

In [54]:
train_i=train_i.reshape(50000,32*32*3)
train_i=train_i.astype('float32')/255
test_i=test_i.reshape(10000,32*32*3)
test_i=test_i.astype('float32')/255

In [14]:
test_i.shape

(10000, 32, 32, 3)

In [16]:
train_i

array([[1.        , 1.        , 1.        , ..., 0.5411765 , 0.6784314 ,
        0.30980393],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.98039216, 0.98039216, 0.972549  , ..., 0.9098039 , 0.9019608 ,
        0.89411765],
       ...,
       [0.972549  , 0.95686275, 0.9490196 , ..., 0.8       , 0.8039216 ,
        0.8039216 ],
       [0.6117647 , 0.6039216 , 0.5372549 , ..., 0.6392157 , 0.6039216 ,
        0.49411765],
       [0.12156863, 0.2627451 , 0.47843137, ..., 0.15686275, 0.14509805,
        0.2627451 ]], dtype=float32)

In [17]:
test_i

array([[0.78039217, 0.84313726, 0.9764706 , ..., 0.6901961 , 0.6431373 ,
        0.7176471 ],
       [0.44313726, 0.50980395, 0.38431373, ..., 0.32941177, 0.36078432,
        0.2627451 ],
       [0.23921569, 0.3529412 , 0.47058824, ..., 0.5254902 , 0.38431373,
        0.34901962],
       ...,
       [0.09411765, 0.14901961, 0.12156863, ..., 0.23529412, 0.36862746,
        0.21176471],
       [0.3372549 , 0.3529412 , 0.3137255 , ..., 0.47058824, 0.45882353,
        0.42745098],
       [0.9647059 , 0.9647059 , 0.9490196 , ..., 0.57254905, 0.7137255 ,
        0.4627451 ]], dtype=float32)

In [18]:
test_l

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [63]:
network.fit(train_i,train_l,batch_size=200,epochs=5)

Epoch 1/5
250/250 [==============================] - 12s 47ms/step - loss: 3.0538 - accuracy: 0.2675
Epoch 2/5
250/250 [==============================] - 10s 42ms/step - loss: 3.0458 - accuracy: 0.2670
Epoch 3/5
250/250 [==============================] - 11s 44ms/step - loss: 3.0382 - accuracy: 0.2694
Epoch 4/5
250/250 [==============================] - 11s 43ms/step - loss: 3.0307 - accuracy: 0.2703
Epoch 5/5
250/250 [==============================] - 11s 42ms/step - loss: 3.0231 - accuracy: 0.2724


In [64]:
test_loss,test_accuracy=network.evaluate(test_i,test_l)

313/313 [==============================] - 2s 6ms/step - loss: 3.2737 - accuracy: 0.2321
